### ISSUE TITLE
Create Database Collections

### ISSUE THREAD

**Issue by wsciaroni** [uah-cpe-sd-2020/myportion_app#29]
We need to have pet data and feeder data stored in collections.  @GuassianFlux Had some ideas on how we might organize this.

**Comment by GuassianFlux** [comment]
@wsciaroni What did you envision the output of this story being? I can enter some mock information into the database that follows the diagram in the Google drive, but that information would only be good to read from. For the stories where we want to dynamically create new pet profiles, or even new feeders, the collections should be made upon request, like the user profiles. If it is actually how we should organize the collections, I can revisit the diagram we've made and make the appropriate changes.

**Comment by GuassianFlux** [comment]
I entered some example data into the Firestore to demonstrate how we may want to store it in the future.

**Comment by wsciaroni** [comment]
I think entering example data may be sufficient.  So long as the collections exist and you've defined a way for people to store/retrieve.  The storage organization will be important to how people set up all our interactions with the database, so I was hoping to get that well defined.

Maybe along with getting it in the database, you could document it in some `.md` file?

Thank you!

**Comment by GuassianFlux** [comment]
@CollierA13j 
I was hesitant to include the diagram as an image because it would mean one of two things. The image could be sourced locally from the repository but then it is attached to the source code. Alternatively, the image could be hosted on some external website and sourced from there, but then there is the hassle of making an account and all that. Let me know what you think, and we can take the appropriate path before I merge this.
